In [1]:
import numpy as np

In [32]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [33]:
add = a1+a2
add

array([ 7,  9, 11, 13, 15])

In [34]:
a2**a1

array([     6,     49,    512,   6561, 100000])

In [35]:
l =[1,2,3,4,5]
arr = np.array(l)

In [36]:
arr + 10

array([11, 12, 13, 14, 15])

In [37]:
arr2 = np.arange(1,26).reshape(5,5)
arr2


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [38]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [49]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
slice = a[:5]
slice=slice + 10
slice

array([11, 12, 13, 14, 15])

In [51]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a
b=a.copy()

In [53]:
b[0] =99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9])

In [54]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
A = np.array([[1,2],[3,4]])
B = np.array([[4,5],[6,7]])

In [60]:
A

array([[1, 2],
       [3, 4]])

In [61]:
B

array([[4, 5],
       [6, 7]])

In [66]:
dot_product=np.dot(A,B)
dot_product

array([[16, 19],
       [36, 43]])

In [67]:
dot_product.T

array([[16, 36],
       [19, 43]])

In [68]:
A = np.array([1,2,3,4])
B = np.array([5,6,7,8])

In [69]:
A

array([1, 2, 3, 4])

In [70]:
B

array([5, 6, 7, 8])

In [71]:
np.vstack((A,B))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [72]:
np.hstack((A,B))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [73]:
np.column_stack((A,B))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [77]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [82]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [83]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]