In [32]:
import numpy as np

In [33]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [34]:
arr[6]

np.int64(17)

In [35]:
arr[9]

np.int64(20)

In [36]:
arr[1:5]

array([12, 13, 14, 15])

In [37]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [38]:
arr[5,4]

np.int64(30)

In [39]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [40]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [41]:
arr = arr[:,2]
arr

array([ 3,  8, 13, 18, 23, 28])

In [42]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [44]:
bool_index = arr%2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [45]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])